# Generated by Django 5.1 on 2024-08-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerpage',
            old_name='image',
            new_name='imag',
        ),
    ]
