# Generated by Django 5.1 on 2024-08-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0002_rename_image_careerpage_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpage',
            name='imag',
            field=models.ImageField(upload_to='careers/media'),
        ),
    ]
