# Generated by Django 5.1 on 2024-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0003_alter_careerpage_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpage',
            name='imag',
            field=models.ImageField(upload_to='z_protofolio/media'),
        ),
    ]
