# Generated by Django 5.1 on 2024-08-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0005_formdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='CareerFormData',
        ),
    ]
