# Generated by Django 5.1 on 2024-08-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0006_rename_formdata_careerformdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_text', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('finish_text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='z_protofolio/media')),
            ],
        ),
    ]
