# Generated by Django 5.1 on 2024-08-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0007_contactuspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuspage',
            old_name='location',
            new_name='location_text',
        ),
    ]
