# Generated by Django 5.1 on 2024-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0009_contactusformdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpage',
            name='imag',
            field=models.ImageField(upload_to='z_protofolio/media/career'),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='image',
            field=models.ImageField(upload_to='z_protofolio/media/contactus'),
        ),
    ]
