# Generated by Django 5.1 on 2024-08-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0010_alter_careerpage_imag_alter_contactuspage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleUpdatPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_name', models.CharField(max_length=100)),
                ('discreption', models.TextField()),
                ('Image', models.ImageField(upload_to='z_protofolio/media/updates')),
                ('read_more_text', models.CharField(max_length=255)),
                ('is_home', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AllUpdatesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('updates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_protofolio.singleupdatpage')),
            ],
        ),
    ]
