# Generated by Django 5.1 on 2024-08-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0011_singleupdatpage_allupdatespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allupdatespage',
            name='updates',
        ),
        migrations.AddField(
            model_name='allupdatespage',
            name='updates',
            field=models.ManyToManyField(to='z_protofolio.singleupdatpage'),
        ),
    ]
