# Generated by Django 5.0.1 on 2024-08-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("z_protofolio", "0012_remove_allupdatespage_updates_allupdatespage_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allupdatespage",
            name="updates",
            field=models.ManyToManyField(
                related_name="updates", to="z_protofolio.singleupdatpage"
            ),
        ),
    ]
