# Generated by Django 5.1 on 2024-08-27 12:25

import z_protofolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0013_alter_allupdatespage_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFacilitiesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_info_title', models.CharField(max_length=100)),
                ('facility_info_text', models.CharField(max_length=255)),
                ('facility_info_image', models.ImageField(upload_to='z_protofolio/media/projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='z_protofolio/media/projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('svg_logo', models.ImageField(upload_to='z_protofolio/media/projects')),
                ('project_discription', models.TextField()),
                ('location_title', models.CharField(max_length=100)),
                ('location_text', models.CharField(max_length=255)),
                ('category_title', models.CharField(max_length=100)),
                ('category_text', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='z_protofolio/media/projects')),
                ('overview_title', models.CharField(max_length=100)),
                ('overview_text', models.TextField()),
                ('poucher_pdf', models.FileField(upload_to='z_protofolio/media/poucher', validators=[z_protofolio.models.validate_pdf])),
                ('facility_title', models.CharField(max_length=100)),
                ('facility_text', models.CharField(max_length=255)),
                ('gallery_title', models.CharField(max_length=100)),
                ('gallery_text', models.CharField(max_length=255)),
                ('location_footer_text', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('map_url', models.URLField(validators=[z_protofolio.models.maps_url])),
                ('ifram_map_url', models.URLField(validators=[z_protofolio.models.maps_url])),
                ('contact_us_text', models.CharField(max_length=255)),
                ('facities', models.ManyToManyField(related_name='facilities_info', to='z_protofolio.projectfacilitiesinfo')),
                ('gallery_images', models.ManyToManyField(related_name='gallery_images', to='z_protofolio.projectgallery')),
            ],
        ),
    ]
