# Generated by Django 5.1 on 2024-08-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0014_projectfacilitiesinfo_projectgallery_projectpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectGallery',
            new_name='ProjectGalleryImage',
        ),
    ]
