# Generated by Django 5.1 on 2024-08-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0016_remove_projectpage_facities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfacilitiesinfo',
            name='project_page',
        ),
        migrations.RemoveField(
            model_name='projectgalleryimage',
            name='project_page',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='facities',
            field=models.ManyToManyField(related_name='facilities_info', to='z_protofolio.projectfacilitiesinfo'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gallery_images',
            field=models.ManyToManyField(related_name='gallery_images', to='z_protofolio.projectgalleryimage'),
        ),
        migrations.CreateModel(
            name='ProjectPageFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_protofolio.projectfacilitiesinfo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_protofolio.projectpage')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_protofolio.projectgalleryimage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_protofolio.projectpage')),
            ],
        ),
    ]
