# Generated by Django 5.1 on 2024-08-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0017_remove_projectfacilitiesinfo_project_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='facities',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='gallery_images',
        ),
    ]
