# Generated by Django 5.1 on 2024-08-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0018_remove_projectpage_facities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpagegallery',
            name='gallery_image',
        ),
        migrations.RemoveField(
            model_name='projectpagegallery',
            name='project',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='facities',
            field=models.ManyToManyField(related_name='facilities_info', to='z_protofolio.projectfacilitiesinfo'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gallery_images',
            field=models.ManyToManyField(related_name='gallery_images', to='z_protofolio.projectgalleryimage'),
        ),
        migrations.DeleteModel(
            name='ProjectPageFacilities',
        ),
        migrations.DeleteModel(
            name='ProjectPageGallery',
        ),
    ]
