# Generated by Django 5.1 on 2024-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0020_remove_projectpage_facities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='gallery_title',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_year',
            field=models.IntegerField(default=2024),
        ),
    ]
