# Generated by Django 5.1 on 2024-08-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0021_remove_projectpage_gallery_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allupdatespage',
            name='updates',
        ),
    ]
