# Generated by Django 5.1 on 2024-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0023_allprojectspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
