# Generated by Django 5.1 on 2024-08-28 15:10

import z_protofolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0024_projectpage_is_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('first_title', models.CharField(max_length=255)),
                ('second_title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='z_protofolio/media/apoutus')),
                ('main_description', models.TextField()),
                ('second_section_title', models.CharField(max_length=255)),
                ('second_section_description', models.TextField()),
                ('company_profile', models.FileField(upload_to='z_protofolio/media/company_profile', validators=[z_protofolio.models.validate_pdf])),
                ('our_mission_title', models.CharField(max_length=255)),
                ('our_mission_text', models.TextField()),
                ('our_mission_image', models.ImageField(upload_to='z_protofolio/media/apoutus')),
                ('our_vision_title', models.CharField(max_length=255)),
                ('our_vision_text', models.TextField()),
                ('our_vision_image', models.ImageField(upload_to='z_protofolio/media/apoutus')),
                ('mutltible_section_title', models.CharField(max_length=100)),
                ('our_founders_title', models.CharField(max_length=100)),
                ('contactus_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=100)),
                ('founder_title', models.CharField(max_length=100)),
                ('founder_description', models.TextField()),
                ('founder_image', models.ImageField(upload_to='z_protofolio/media/apoutus')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('section_text', models.CharField(max_length=255)),
                ('section_description', models.TextField()),
                ('section_image', models.ImageField(upload_to='z_protofolio/media/apoutus')),
            ],
        ),
    ]
