# Generated by Django 5.1 on 2024-08-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0025_apoutuspage_founder_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApoutUsPage',
            new_name='AboutUsPage',
        ),
    ]
