# Generated by Django 5.1 on 2024-08-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0026_rename_apoutuspage_aboutuspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Founder',
            new_name='AboutUsFounder',
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='AboutUsSection',
        ),
    ]
