# Generated by Django 5.1 on 2024-08-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0027_rename_founder_aboutusfounder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusfounder',
            name='about_us_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='z_protofolio.aboutuspage'),
        ),
        migrations.AddField(
            model_name='aboutussection',
            name='about_us_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='z_protofolio.aboutuspage'),
        ),
    ]
