# Generated by Django 5.0.1 on 2024-08-28 19:34

import django.db.models.deletion
import z_protofolio.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("z_protofolio", "0028_aboutusfounder_about_us_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="z_protofolio/media/home")),
                ("slider_title", models.CharField(max_length=255)),
                ("about_title", models.CharField(max_length=255)),
                ("about_image", models.ImageField(upload_to="")),
                ("years_number", models.PositiveIntegerField()),
                ("years_text", models.CharField(max_length=155)),
                ("employee_numbers", models.CharField(max_length=50)),
                ("employee_text", models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name="HomePageSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slider_image_video",
                    models.FileField(
                        upload_to="z_protofolio/media/slider",
                        validators=[z_protofolio.models.validate_slider],
                    ),
                ),
                (
                    "homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slider_content",
                        to="z_protofolio.homepage",
                    ),
                ),
            ],
        ),
    ]
