# Generated by Django 5.1 on 2024-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0029_homepage_homepageslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='phone_number',
            field=models.IntegerField(default=1),
        ),
    ]
