# Generated by Django 5.1 on 2024-08-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0030_contactuspage_email_contactuspage_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='description',
            field=models.TextField(default='loooooooooooooooooool'),
        ),
    ]
