# Generated by Django 5.1 on 2024-08-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0031_contactuspage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuspage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
