# Generated by Django 5.1 on 2024-08-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0032_alter_contactuspage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='projectpage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='z_protofolio.projectcategories'),
        ),
    ]
