# Generated by Django 5.1 on 2024-08-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0033_projectcategories_projectpage_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcategories',
            old_name='name',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='z_protofolio.projectcategories'),
        ),
    ]
