# Generated by Django 5.1 on 2024-08-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0034_rename_name_projectcategories_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcategories',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='z_protofolio.projectcategories'),
        ),
    ]
