# Generated by Django 5.1 on 2024-08-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0035_rename_category_projectcategories_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='category_text',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='category_title',
        ),
    ]
