# Generated by Django 5.1 on 2024-08-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_protofolio', '0036_remove_projectpage_category_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='contact_us_button_title',
            field=models.CharField(default='contact us', max_length=155),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gallery_second_text',
            field=models.CharField(default='second text here', max_length=255),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='get_direction_button_title',
            field=models.CharField(default='get direction', max_length=155),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='poucher_pdf_button',
            field=models.CharField(default='download it', max_length=155),
        ),
    ]
