# Generated by Django 5.0.1 on 2024-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("z_protofolio", "0038_aboutuspage_contactus_button_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="z_protofolio/media/footer")),
                ("footer_long_text", models.TextField()),
                ("first_small_text", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("second_small_text", models.CharField(max_length=250)),
                ("theird_small_text", models.CharField(max_length=250)),
                ("theird_long_text", models.TextField()),
                ("facebook_url", models.URLField()),
                ("instegram_url", models.URLField()),
                ("linkedin_url", models.URLField()),
            ],
        ),
    ]
