# Generated by Django 5.0.1 on 2024-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "z_protofolio",
            "0040_remove_footer_first_small_text_remove_footer_logo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="careerpage",
            name="webp_image_path",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
