# Generated by Django 5.1 on 2024-09-03 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("z_protofolio", "0041_careerpage_webp_image_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careerpage",
            name="webp_image_path",
        ),
    ]
